[project]
name = "nonebot-plugin-alconna"
version = "0.2.4"
description = "Alconna Adapter for Nonebot"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "nonebot2>=2.0.0rc3",
    "arclet-alconna>=1.5.5",
    "arclet-alconna-tools>=0.4.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
keywords = [
    "command",
    "argparse",
    "cli",
    "alconna",
    "nonebot",
]
[project.urls]
repository = "https://github.com/ArcletProject/nonebot-plugin-alconna"

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "fix-future-annotations>=0.5.0",
    "nonebot-adapter-onebot>=2.2.1",
    "nonebot-adapter-feishu>=2.0.0b6",
    "nonebot-adapter-console>=0.3.2",
]
[tool.pdm.build]
includes = ["src/nonebot_plugin_alconna"]