[project]
name = "nonebot-plugin-alconna"
version = "0.7.0"
description = "Alconna Adapter for Nonebot"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "nonebot2>=2.0.0rc4",
    "arclet-alconna<2.0.0, >=1.7.7",
    "arclet-alconna-tools<0.7.0, >=0.6.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
keywords = [
    "command",
    "argparse",
    "cli",
    "alconna",
    "nonebot",
]
[project.urls]
repository = "https://github.com/ArcletProject/nonebot-plugin-alconna"

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "nonebot2>=2.0.0",
    "fix-future-annotations>=0.5.0",
    "nonebot-adapter-onebot>=2.2.3",
    "nonebot-adapter-feishu>=2.0.0b8",
    "nonebot-adapter-console>=0.3.2",
    "nonebot-adapter-ding>=2.0.0a16",
    "nonebot-adapter-mirai2>=0.0.22",
    "nonebot-adapter-minecraft>=0.1.1",
    "nonebot-adapter-ntchat>=0.3.5",
    "nonebot-adapter-qqguild>=0.2.2",
    "nonebot-adapter-telegram>=0.1.0b10",
]
[tool.pdm.build]
includes = ["src/nonebot_plugin_alconna"]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = false
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["nonebot", "tests"]
extra_standard_library = ["typing_extensions"]